print ("Expressie",5, "uitkomst" ,5, "type", type(5))
print ("Expressie",5.0, "uitkomst", 5.0,"type", type(5.0))
print ("Expressie", "5 % 2", "uitkomst", 5 % 2,"type", type(5 % 2))
print ("Expressie","5 > 1", "uitkomst", 5 > 1, "type", type(5 > 1))
print ("Expressie", "'5'","uitkomst", "'5'","type", type('5'))
print ("Expressie", "5 * 2", "uitkomst", 5 * 2,"type", type(5 * 2))
